# Generated by Django 5.0.1 on 2024-01-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_image_alter_image_user_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
