# Generated by Django 5.0.1 on 2024-01-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='excluded_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
    ]
