# Generated by Django 5.0.1 on 2024-02-10 20:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', validators=[api.models.validate_image_format], verbose_name='img'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
