# Generated by Django 5.0.1 on 2024-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
